
/*
select minerals_and_inorganic.name, percentile_disc(0.50) within group (order by minerals_and_inorganic.value)
from minerals_and_inorganic
group by minerals_and_inorganic.name;
*/

// "Arginin": {"val": 627.59, "i": -1} change to this form where -1 is negative and "i" undefined otherwise.
const thresholds = {
    "aminoAcids": {
        "Alanin": {"val": 330},
        "Arginin": {"val": 395},
        "Asparaginsyre": {"val": 527},
        "Cystin": {"val": 93},
        "Glutaminsyre": {"val": 1650},
        "Glycin": {"val": 345},
        "Histidin": {"val": 345},
        "Hydroxyprolin": {"val": 0},
        "Isoleucin": {"val": 365},
        "Leucin": {"val": 639},
        "Lysin": {"val": 312},
        "Methionin":{"val": 146},
        "Phenylalanin": {"val": 428},
        "Prolin": {"val": 570},
        "Serin": {"val": 439},
        "Threonin": {"val": 269},
        "Tryptofan": {"val": 87},
        "Tyrosin": {"val": 221},
        "Valin": {"val": 446}
    },
    "carbohydrates": {
        "Andre sukkerarter": {"val": 0},
        "Cellulose": {"val": 0},
        "Crude fibre": {"val": 0.6},
        "Disaccharider, total": {"val": 0.55},
        "Fruktose": {"val": 0.0611},
        "Galaktose": {"val": 0},
        "Glukose": {"val": 0.06},
        "Hexose":{"val": 0},
        "IDF":{"val": 7.3},
        "Inositol":{"val": 3.3},
        "Laktose":{"val": 0},
        "Lignin": {"val": 0},
        "Maltitol":{"val": 9.09},
        "Maltose":{"val": 0},
        "Maltotriose":{"val": 0},
        "Mannitol":{"val": 0},
        "Monosaccharider, total": {"val": 0.253},
        "Neutr.Det.Fibre (NDF)":{"val": 1.1},
        "Pentose": {"val": 0},
        "Raffinose":{"val": 0},
        "Sakkarose":{"val": 0.05, "i": -1},
        "SDFP":{"val": 1.3},
        "SDFS":{"val": 1},
        "Sorbitol":{"val": 0},
        "Stivelse":{"val": 0},
        "Sukkeralkoholer, total":{"val": 0},
        "Sukkerarter, total":{"val": 1.35},
        "Uronic Acid":{"val": 0}
    },
    "fattyAcids": {
        "Andre fedtsyrer":{"val": 0.01},
        "Fedtsyrer, total":{"val": 3.912},
        "Sum monoumættede":{"val": 1.375},
        "Sum mættede":{"val": 1.311},
        "Sum n-3 fedtsyrer":{"val": 0.112},
        "Sum n-6 fedtsyrer":{"val": 0.469},
        "Sum polyumættede":{"val": 0.693},
        "Transfedtsyrer, total":{"val": 0.024}
    },
    "minerals": { 
        "Silicium, Si": {"val": 0.5},
        "Cadmium, Cd": {"val": 0.9},
        "Fosfor, P": {"val": 120},
        "Arsen, As": {"val": 0.7},
        "Cobolt, Co": {"val": 1},
        "Aluminium, Al": {"val": 0.3},
        "Chlorid, Cl": {"val": 658},
        "Nikkel, Ni": {"val": 3.51},
        "Tin, Sn": {"val": 19},
        "Kalium, K": {"val": 204},
        "Brom, Br": {"val": 200},
        "Mangan, Mn": {"val": 0.074},
        "Chrom, Cr": {"val": 2.18},
        "Zink, Zn": {"val": 0.78},
        "Bor, B": {"val": 40},
        "Natrium, Na": {"val": 68},
        "Jod, I": {"val": 2.3},
        "Kviksølv, Hg": {"val": 0.1},
        "Molybdæn, Mo": {"val": 2},
        "Selen, Se": {"val": 3},
        "Calcium, Ca": {"val": 28.7},
        "Magnesium, Mg": {"val": 20},
        "Svovl, S": {"val": 140},
        "Kobber, Cu": {"val": 0.086},
        "Bly, Pb": {"val": 1.25},
        "Arsen uorganisk": {"val": 1.55},
        "Fluor, F": {"val": 40},
        "Jern, Fe": {"val": 0.8},
        "Rubidium, Rb": {"val": 270}
    },
    "organicAcids": {
        "Benzoesyre":{"val": 0.03},
        "Citronsyre":{"val": 0.186},
        "D-mælkesyre":{"val": 0.13},
        "Eddikesyre":{"val": 5},
        "L-mælkesyre":{"val": 0.65},
        "Mælkesyre: total":{"val": 0.94},
        "Organiske syrer: tot.":{"val": 0.6},
        "Oxalsyre":{"val": 0.21},
        "Propionsyre":{"val": 0},
        "Æblesyre":{"val": 0.0069},
    },
    "sterols": {
        "Cholesterol": {"val": 0}
    },
    "vitamins": {
        "25-hydroxy D3-vitamin":{"val": 0.086},
        "25-hydroxyergocalciferol":{"val": 0},
        "A-vitamin":{"val": 4.17},
        "alfa-tokoferol":{"val": 0.434},
        "alfa-tokotrienol":{"val": 0.05},
        "B1-vitamin":{"val": 0.063},
        "B12-vitamin":{"val": 0},
        "B2-vitamin, riboflavin":{"val": 0.1},
        "B6-vitamin":{"val": 0.105},
        "beta-caroten":{"val": 0},
        "Biotin":{"val": 1.63},
        "C-vitamin":{"val": 0.1},
        "D-vitamin":{"val": 0},
        "D2 ergocalciferol":{"val": 0},
        "D3-vitamin":{"val": 0},
        "delta-tokoferol":{"val": 0},
        "E-vitamin":{"val": 0.42},
        "Folat":{"val": 15},
        "Frit folat":{"val": 4},
        "gamma-tokoferol":{"val": 7.6},
        "HET: hydroxyethylthiazole":{"val": 0},
        "K1-vitamin":{"val": 0},
        "L-ascorbinsyre":{"val": 0},
        "L-dehydroascorbinsyre":{"val": 1.7},
        "Niacin":{"val": 0.8},
        "Niacinækvivalent":{"val": 1.56},
        "Pantothensyre":{"val": 0.337},
        "Retinol":{"val": 0},
        "thiamin":{"val": 0.044}
    }
};

export {thresholds};